name: daily-agent

on:
  # UTC schedule: 09:00 in Taipei/Singapore (UTC+8) == 01:00 UTC
  schedule:
    - cron: "0 1 * * *"
  # manual run button
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-bots-and-publish-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # (Optional) Run your individual bots.
      # We keep them non-fatal for now so one failure doesn't stop JSON publish.
      - name: Run bots (non-fatal)
        run: |
          set -x
          python pi_cycle_top_bot.py || true
          python ahr_999_bot.py || true
          python morning_brief_bot_v8.py || true
          python iSunOne_Wealth_Bot_v4o.py || true
          python iSunOne_Wealth_Bot_v4s.py || true 2>/dev/null || true

      - name: Generate reports/daily_report.json
        run: |
          python .github/scripts/aggregate_to_json.py
          echo "----"; cat reports/daily_report.json; echo "----"

      - name: Commit JSON back to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update reports/daily_report.json [skip ci]"
          file_pattern: reports/daily_report.json
